# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NodeStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeStatus(object):
    def setupUi(self, NodeStatus):
        NodeStatus.setObjectName("NodeStatus")
        NodeStatus.resize(695, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NodeStatus.sizePolicy().hasHeightForWidth())
        NodeStatus.setSizePolicy(sizePolicy)
        NodeStatus.setStyleSheet("*{    \n"
"    font-family:微软雅黑;\n"
"    font-size:15px;\n"
"    color: #1d649c;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(NodeStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.guiplot = GLViewWidget(NodeStatus)
        self.guiplot.setObjectName("guiplot")
        self.verticalLayout.addWidget(self.guiplot)

        self.retranslateUi(NodeStatus)
        QtCore.QMetaObject.connectSlotsByName(NodeStatus)

    def retranslateUi(self, NodeStatus):
        _translate = QtCore.QCoreApplication.translate
        NodeStatus.setWindowTitle(_translate("NodeStatus", "节点状态"))
from pyqtgraph.opengl import GLViewWidget
