# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SystemStatus(object):
    def setupUi(self, SystemStatus):
        SystemStatus.setObjectName("SystemStatus")
        SystemStatus.resize(719, 702)
        SystemStatus.setStyleSheet("*{    \n"
"    font-family:微软雅黑;\n"
"    font-size:15px;\n"
"    color: #1d649c;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(SystemStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(SystemStatus)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.guiplot_consensus = GraphicsLayoutWidget(self.groupBox)
        self.guiplot_consensus.setObjectName("guiplot_consensus")
        self.verticalLayout_2.addWidget(self.guiplot_consensus)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(SystemStatus)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.guiplot_growthRate = GraphicsLayoutWidget(self.groupBox_3)
        self.guiplot_growthRate.setObjectName("guiplot_growthRate")
        self.verticalLayout_3.addWidget(self.guiplot_growthRate)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(SystemStatus)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.groupBox_2)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.rate_anti = QtWidgets.QLabel(self.groupBox_2)
        self.rate_anti.setText("")
        self.rate_anti.setObjectName("rate_anti")
        self.horizontalLayout.addWidget(self.rate_anti)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 6)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(SystemStatus)
        QtCore.QMetaObject.connectSlotsByName(SystemStatus)

    def retranslateUi(self, SystemStatus):
        _translate = QtCore.QCoreApplication.translate
        SystemStatus.setWindowTitle(_translate("SystemStatus", "系统状态"))
        self.groupBox.setTitle(_translate("SystemStatus", "共识时间"))
        self.groupBox_3.setTitle(_translate("SystemStatus", "生长速率"))
        self.groupBox_2.setTitle(_translate("SystemStatus", "统计"))
        self.label1.setText(_translate("SystemStatus", "防篡改率："))
from pyqtgraph import GraphicsLayoutWidget
